spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distributed_lock?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

#logging:
#  level:
#    com.example.distributedlock.dao: debug #一定要加这一行指定目录，不然报错

