name: Auto Sidebar

on:
  push:
    branches:
      - main

jobs:
  run-coupons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run autoSidebar.js
        run: node autoSidebar.js

      - name: Commit and push changes
        run: |
          git config --global user.name "zzq8"
          git config --global user.email "1024zzq@gmail.com"
          git config --global user.password ${{ secrets.SECRET_TOKEN }}
          git add -A
          git commit -m "Update sidebar"
          git push
