name: Auto Sidebar

on:
  push:
    branches:
      - main

jobs:
  run-coupons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run autoSidebar.js
        run: |
          cd $GITHUB_WORKSPACE #将工作目录更改为仓库的根目录
          node autoSidebar.js
