name: Auto Sidebar

on:
  push:
    branches:
      - main  # 指定要触发工作流程的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci  # 或者使用您的依赖安装命令

      - name: Run autoSidebar.js
        run: node autoSidebar.js
